### ISSUE TITLE
Unable to download correct model

### ISSUE THREAD

**Issue by lz2470** [ColfaxResearch/YOLO-Object-Detection#3]
Hi,
   When I run config.py, it was not able to download the model. I tried with the tiny Yolo model I downloaded on Nov.2017 and newest model shared on the darknet website. They both dont work. Could you please provide correct model or update config.py. Thanks.
Result using old model:
`Traceback (most recent call last):
  File "config.py", line 92, in <module>
    obj.run()
  File "config.py", line 83, in run
    self.convert(key)
  File "config.py", line 68, in convert
    assert False,'Format Error: Darknet weights might have been updated'
AssertionError: Format Error: Darknet weights might have been updated
`
Result using newest model:
`Traceback (most recent call last):
  File "config.py", line 92, in <module>
    obj.run()
  File "config.py", line 83, in run
    self.convert(key)
  File "config.py", line 54, in convert
    w =  np.transpose(block[4*shape[3]:].reshape(dnshape),(2,3,1,0))
ValueError: total size of new array must be unchanged
`

**Comment by shubhajitml** [comment]
@lz2470 same problem here
@sangameshnr Please tell us, what's wrong happening with the code

**Comment by sangameshnr** [comment]
Hi,
Thank you for getting back to us. Darknet has deleted the tiny-yolo and yolo-v2 weight files that were there before. There is a link to the old yolo files but they too have the new weights trained on MSCOCO. I will see how I can upload the old yolo weights that have been trained on PASCAL VOC dataset.

**Comment by sangameshnr** [comment]
I have added the weight files . Please try now

**Comment by shubhajitml** [comment]
Thanks, @sangameshnr , it worked but still having some problems. There was a typo in **_line no  14_** in `config.py`.  (Change `xrange` to `range` )
After correction when I  run the code, the OpenCV window pops up and closed showing the following:
```
Frame rate : 1.091701 fps
Frame rate : 2.658634 fps
Frame rate : 3.261291 fps
[ INFO:0] Initialize OpenCL runtime...
Traceback (most recent call last):
  File "webcam_inference.py", line 79, in <module>
    draw_boxes(img2,box_preds)
  File "webcam_inference.py", line 46, in draw_boxes
    **cv2.putText(img[idx], class_names[i], (int(left), int(bot)), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 0, 0), 2)**
**TypeError: bad argument type for built-in operation**
```
Thanks in advance.

**Comment by sangameshnr** [comment]
@shubhajitml , it is not a typo, xrange is removed from the recent python version.
https://www.pythoncentral.io/how-to-use-pythons-xrange-and-range/

What version of python and OpenCV are you using?

**Comment by shubhajitml** [comment]
@sangameshnr Sorry, Sir, I was unaware of `xrange` used in python 2. I am using python 3.6.5 and opencv 3.3.1. But here the error is due to some other problem:
 `File "webcam_inference.py", line 46, in draw_boxes
    **cv2.putText(img[idx], class_names[i], (int(left), int(bot)), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 0, 0), 2)**
**TypeError: bad argument type for built-in operation**`

**Comment by sangameshnr** [comment]
Hi @shubhajitml , one of the requirements mentioned in this repository (README.md) specifically mentions  Python 2.7. I have noticed some syntax changes between python 2.7 and python 3. The code was originally developed in python 2.7. So could you please try it on pyhton 2.7 ?
Also, try this for tensorflow, `pip install tensorflow==1.4.1` , because I am currently using this along with python 2.7 and it works fine.
Please let us know how it goes.

**Comment by shubhajitml** [comment]
Ok, Sir. Let me try.

**Comment by shubhajitml** [comment]
@sangameshnr it's working fine with python 2.7 environment.
Any suggestion for modifying the code for Python 3 environment.

**Comment by sangameshnr** [comment]
Hi @shubhajitml ,
I would start with the draw_boxes function in the inference.py . I have used the list generators which are supported in python 2.7, check if there is any change in python 3. Also, check the cv2 methods used in the same function.

**Comment by ZhangQuentin** [comment]
> @sangameshnr Sorry, Sir, I was unaware of `xrange` used in python 2. I am using python 3.6.5 and opencv 3.3.1. But here the error is due to some other problem:
> `File "webcam_inference.py", line 46, in draw_boxes **cv2.putText(img[idx], class_names[i], (int(left), int(bot)), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 0, 0), 2)** **TypeError: bad argument type for built-in operation**`

This error is because of the type of "class_names[i]", please use "class_names[i].decode("utf-8")" instead of it.

**Comment by ZhangQuentin** [comment]
> I have added the weight files . Please try now

Year! I have try your weight,and it work well. When I try the new weight such as yolov2.weight, it doesn't work, can you give another code to use the new weight. ｗait for your good codes.
